### ISSUE TITLE
Progress support with WebSocket adapter

### ISSUE THREAD

**Issue by dmitryuk** [qchateau/packio#64]
I have WebSocket server over JSON-RPC (MR https://github.com/qchateau/packio/pull/60), that can do long (from 1 to 30 minutes) the API call and can generate progress (%) with extra data (remaining time, sec).
Can I do progress somehow?

**Comment by qchateau** [comment]
Hello, JSON-RPC doesn't support streaming RPC do there is no way to have any kind of feedback on the progress of the built via built-in features. If you want to have progress feedback you'll have to either:
- add a second endpoint to report a client's progress (via a call token for instance)
- do multiple small calls instead of one long call

**Comment by dmitryuk** [comment]
Thanks!
